name: hunarlink
description: AI-powered service orchestrator for Pakistan informal economy
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^4.9.0
  cloud_firestore: ^6.4.1
  flutter_local_notifications: any
  http: ^1.6.0
  cupertino_icons: ^1.0.6
  speech_to_text: ^7.4.0
  geolocator: ^11.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_launcher_icon.png"
  remove_alpha_ios: true
  adaptive_icon_background: "#F7F2EA"
  adaptive_icon_foreground: "assets/icon/app_launcher_foreground.png"

flutter:
  uses-material-design: true

  fonts:
    - family: Plus Jakarta Sans
      fonts:
        - asset: assets/fonts/PlusJakartaSans-Regular.ttf
        - asset: assets/fonts/PlusJakartaSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/PlusJakartaSans-ExtraBold.ttf
          weight: 800

  assets:
    - assets/images/
    - assets/icon/
